import Head from 'next/head'
import Navbar from '../components/navbar/Navbar'
import { useState } from 'react'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main onClick={()=> setHamIsOn(false)}>
        <h1>Index</h1>
        <h1>Index</h1>
        <h1>Index</h1>
        <h1>Index</h1>
        <h1>Index</h1>
        <h1>Index</h1>
      
      </main>
    </>
  )
}
