import Head from 'next/head'
import HomePage from '../components/HomePage/HomePage'
export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HomePage />
    </>
  )
}
